"""add resume blob storage

Revision ID: 3ce0c78ddfdf
Revises: 
Create Date: 2026-03-24 23:34:02.233210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ce0c78ddfdf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('resume_file', sa.LargeBinary(), nullable=True))
    op.add_column('applications', sa.Column('resume_mimetype', sa.String(), nullable=True))
    op.drop_column('applications', 'resume_drive_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('resume_drive_link', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('applications', 'resume_mimetype')
    op.drop_column('applications', 'resume_file')
    # ### end Alembic commands ###
