"""add rag fields to application

Revision ID: c30fc38d7377
Revises: 4a1b2c3d4e5f
Create Date: 2026-04-05 18:45:18.670213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c30fc38d7377'
down_revision: Union[str, None] = '4a1b2c3d4e5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('resume_text', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('rag_verdict', sa.String(), nullable=True))
    op.add_column('applications', sa.Column('rag_score', sa.Float(), nullable=True))
    op.add_column('applications', sa.Column('rag_reasoning', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('rag_strengths', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('rag_gaps', sa.Text(), nullable=True))
    op.add_column('applications', sa.Column('rag_recommendation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'rag_recommendation')
    op.drop_column('applications', 'rag_gaps')
    op.drop_column('applications', 'rag_strengths')
    op.drop_column('applications', 'rag_reasoning')
    op.drop_column('applications', 'rag_score')
    op.drop_column('applications', 'rag_verdict')
    op.drop_column('applications', 'resume_text')
    # ### end Alembic commands ###
